### ISSUE TITLE
gerber files

### ISSUE THREAD

**Issue by Pavel7890** [tonyp7/TAS5806M-Audio-Amplifier#1]
Hi Tony, thanks for sharing the project. I am actually working on similar project, so if you could upload gerber files for the amplifier, it would help me greatly.

**Comment by tonyp7** [comment]
Hey I have added the gerber file under hardware

**Comment by Pavel7890** [comment]
Hello, thanks a lot. I just ordered it via jlcpcb. Looking forward to test
it!

Have a great day
